# This workflow will run whatever happens inside a pull request and whenever there's a commit push on
# the code.
name: Node.js test
on:
  push:
    paths:
      - "packages/*/**.*"
      - "cypress/**/*.*"
      - "!LICENSE.md"
      - "!README.md"
  pull_request:
  workflow_dispatch: # This is what allows us to run this workflow manually.

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Install libgconf-2-4
        run: sudo apt-get install libgconf-2-4
      - uses: actions/checkout@v3
      - name: Setup Node.js v16 LTS ğŸ
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies ğŸ“¦
        run: npm ci
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Bootstrap ğŸ¥¾
        run: npm run bootstrap
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Lint ğŸ”
        run: npm run check:lint
      - name: Build the hooks ğŸ› 
        run: npm run build
      - name: Test the hooks âœ”
        uses: cypress-io/github-action@v2
        with:
          start: npm start, npm run start:test-server

      - name: Upload the videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos/*
        
    
