# This workflow will run when a pull request event is triggered (push, open, whatever happens)
name: Node.js test
on:
  pull_request:
    branches: ['main']
  workflow_dispatch: # just in case when you need to trigger the thing manually without pull requests

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Install libgconf-2-4
        run: sudo apt-get install libgconf-2-4 # Don't worry about passwords, sudo won't prompt for any, cuz there isn't a password here.
      - uses: actions/checkout@v2
      - name: Setup Node.js v10 ğŸ
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies ğŸ“¦
        run: npm ci
      - name: Bootstrap ğŸ¥¾
        run: npm run bootstrap
      - name: Lint ğŸ”
        run: npm run check:lint
      - name: Build the hooks ğŸ› 
        run: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v2
    
