# This workflow will run when a pull request event is triggered (push, open, whatever happens)
name: Node.js test
on:
  pull_request:
    branches: ['main']
  workflow_dispatch: # just in case when you need to trigger the thing manually without pull requests

jobs:
  cypress-run:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        node: [10.x, 12.x, 13.x, 14.x, 15.x]
      fail-fast: false
    name: Node.js v${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - name: Install libgconf-2-4
        run: sudo apt-get install libgconf-2-4 # Don't worry about passwords, sudo won't prompt for any, cuz there isn't a password here.
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node }} ğŸ
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies ğŸ“¦
        run: npm ci
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
      - name: Bootstrap ğŸ¥¾
        run: npm run bootstrap
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Lint ğŸ”
        run: npm run check:lint
      - name: Build the hooks ğŸ› 
        run: npm run build
      - name: Test the hooks âœ”
        uses: cypress-io/github-action@v2
        with:
          start: npm start, npm run start:test-server

      - name: Upload the videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos-${{ matrix.os }}-node_${{ matrix.node }}
          path: cypress/videos/*
        
    
